# Generated by Django 4.2.15 on 2024-10-30 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iscas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacoesModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_criado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "checkin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Checkin Pendente", "Checkin Pendente"),
                            ("Checkin Aprovado", "Checkin Aprovado"),
                            ("Checkin Reprovado", "Checkin Reprovado"),
                        ],
                        default="Checkin Pendente",
                        max_length=255,
                    ),
                ),
                (
                    "checkout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Aguardando Checkin", "Aguardando Checkin"),
                            ("Checkout Pendente", "Checkout Pendente"),
                            ("Checkout Aprovado", "Checkout Aprovado"),
                            ("Checkout Reprovado", "Checkout Reprovado"),
                        ],
                        default="Aguardando Checkin",
                        max_length=255,
                    ),
                ),
                (
                    "implantacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Implantada", "Implantada"),
                            ("Pendente", "Pendente"),
                        ],
                        default="Pendente",
                        max_length=255,
                    ),
                ),
                (
                    "viagem",
                    models.CharField(
                        blank=True,
                        choices=[("Iniciada", "Iniciada"), ("Pendente", "Pendente")],
                        default="Pendente",
                        max_length=255,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Em Analise", "Em Analise"),
                            ("Aprovado", "Aprovado"),
                            ("Reprovado", "Reprovado"),
                        ],
                        default="Em Analise",
                        max_length=255,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "isca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="iscas.iscamodel",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="solicitacoesmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("isca",),
                name="isca_ativo_unico",
            ),
        ),
    ]
