# Generated by Django 4.2.15 on 2024-10-30 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_criado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "roles",
                    models.CharField(
                        choices=[
                            ("ADMINISTRADOR", "ADMINISTRADOR"),
                            ("SUPERVISOR", "SUPERVISOR"),
                            ("OPERADOR", "OPERADOR"),
                        ],
                        max_length=13,
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="foto_usuario/")),
                ("email", models.EmailField(blank=True, max_length=155)),
                ("recebe_email", models.BooleanField(default=True)),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entre com telefone colocando apenas numeros: '999999999'. ",
                                regex="^\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
        migrations.AddConstraint(
            model_name="usuariomodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("user",),
                name="user_ativo_unico",
            ),
        ),
    ]
