# Generated by Django 4.2.15 on 2024-10-30 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedores", "0001_initial"),
        ("operacoes", "0001_initial"),
        ("locais_clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IscaModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_criado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Em checkin", "Em checkin"),
                            ("Em checkout", "Em checkout"),
                            ("Pendente iniciar SM", "Pendente iniciar SM"),
                            ("Em rastreamento", "Em rastreamento"),
                            ("Descartado", "Descartado"),
                            ("Reprovado", "Reprovado"),
                            ("Usado", "Usado"),
                            ("Almoxarifado", "Almoxarifado"),
                        ],
                        default="Almoxarifado",
                        max_length=255,
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="foto_isca/")),
                ("numero_isca", models.CharField(max_length=255)),
                (
                    "comunicacao",
                    models.CharField(
                        choices=[
                            ("Radio Frequência", "Radio Frequência"),
                            ("Hibrido", "Hibrido"),
                            ("GPRS", "GPRS"),
                        ],
                        max_length=55,
                    ),
                ),
                ("usuario_cadastrante", models.CharField(blank=True, max_length=255)),
                (
                    "modelo",
                    models.CharField(
                        choices=[
                            ("Retornável", "Retornável"),
                            ("Fake", "Fake"),
                            ("Descartável", "Descartável"),
                        ],
                        max_length=255,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fornecedores.fornecedormodel",
                    ),
                ),
                (
                    "local_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locais_clientes.locaisclientemodel",
                    ),
                ),
                (
                    "operacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operacoes.operacaomodel",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_isca"],
            },
        ),
        migrations.AddConstraint(
            model_name="iscamodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("numero_isca", "fornecedor"),
                name="numero_isca_fornecedor_ativo_unico",
            ),
        ),
    ]
