# Generated by Django 4.2.15 on 2024-10-30 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("solicitacoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_realizado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "bateria",
                    models.CharField(
                        blank=True,
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=50,
                    ),
                ),
                (
                    "posicionamento",
                    models.CharField(
                        blank=True,
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=50,
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "resultado",
                    models.CharField(
                        choices=[("Aprovado", "Aprovado"), ("Reprovado", "Reprovado")],
                        max_length=60,
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[("Checkin", "Checkin"), ("Checkout", "Checkout")],
                        max_length=50,
                    ),
                ),
                ("usuario_responsavel", models.CharField(blank=True, max_length=100)),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solicitacoes.solicitacoesmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
