# Generated by Django 4.2.15 on 2024-10-30 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iscas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RastreamentoModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_criado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_implantacao",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("sm", models.CharField(blank=True, max_length=255)),
                ("nota_fiscal", models.CharField(blank=True, max_length=255)),
                ("manifesto", models.CharField(blank=True, max_length=255)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("motorista", models.CharField(blank=True, max_length=255)),
                (
                    "valor_sm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                ("rota_insercao", models.CharField(blank=True, max_length=255)),
                ("rota_maior_valor", models.CharField(blank=True, max_length=255)),
                ("placa", models.CharField(blank=True, max_length=255)),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Implantada", "Implantada"),
                            ("Em viagem", "Em viagem"),
                            ("Finalizado", "Finalizado"),
                        ],
                        default="Implantada",
                        max_length=255,
                    ),
                ),
                ("data_saida", models.DateTimeField(blank=True, null=True)),
                ("ativo", models.BooleanField(blank=True, default=True)),
                (
                    "isca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="iscas.iscamodel",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RastreamentoAnexoModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="foto_rastreio/")),
                (
                    "rastreamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rastreamentos.rastreamentomodel",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="rastreamentomodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("sm", "isca"),
                name="sm_isca_ativo_unico",
            ),
        ),
    ]
