# Generated by Django 4.2.15 on 2024-10-30 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_criado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cep", models.CharField(blank=True, max_length=8)),
                ("estado_uf", models.CharField(blank=True, max_length=2)),
                ("cidade", models.CharField(blank=True, max_length=150)),
                ("rua", models.CharField(blank=True, max_length=255)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="localmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("nome",),
                name="nome_local_ativo_unico",
            ),
        ),
    ]
