# Generated by Django 4.2.15 on 2024-10-30 13:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FornecedorModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_criado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=155)),
                ("recebe_email", models.BooleanField(default=True)),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entre com telefone colocando apenas numeros: '999999999'. ",
                                regex="^\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="fornecedormodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("nome",),
                name="nome_fornecedores_ativo_unico",
            ),
        ),
    ]
