# Generated by Django 4.2.15 on 2024-10-30 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operacoes", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuariosOperacaoModel",
            fields=[
                (
                    "data_alterado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "data_criado",
                    models.DateTimeField(
                        auto_created=True, blank=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "operacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operacoes.operacaomodel",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usuarios.usuariomodel",
                    ),
                ),
            ],
            options={
                "ordering": ["usuario"],
            },
        ),
        migrations.AddConstraint(
            model_name="usuariosoperacaomodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("operacao", "usuario"),
                name="operacao_usuario_ativo_unico",
            ),
        ),
    ]
